// Volunteer directory grouping + availability + team-aware scheduling.
const AVAILABILITY_OPTIONS=[['weekly','Weekly'],['biweekly','Bi-weekly'],['monthly','Monthly'],['as_needed','As needed'],['specific_mondays','Specific Mondays']];
function availabilityLabel(v){const raw=v?.availability_type||'';const map={weekly:'Weekly',every_monday:'Weekly',biweekly:'Bi-weekly',first_third:'Bi-weekly — 1st & 3rd Mondays',second_fourth:'Bi-weekly — 2nd & 4th Mondays',monthly:'Monthly',first:'Monthly — 1st Monday',second:'Monthly — 2nd Monday',third:'Monthly — 3rd Monday',fourth:'Monthly — 4th Monday',as_needed:'As needed',specific_mondays:'Specific Mondays'};return map[raw]||raw.replaceAll('_',' ')}
function mondayOccurrence(d){return Math.ceil(d.getDate()/7)}
function dateListed(v,date){return data.specific_dates.some(x=>x.volunteer_id===v.id&&x.available_date===date)}
function isVolunteerAvailable(v,date){if(!v)return false;const d=new Date(date+'T12:00:00'),occ=mondayOccurrence(d),raw=v.availability_type||'';if(raw==='weekly'||raw==='every_monday')return true;if(raw==='first_third')return occ===1||occ===3;if(raw==='second_fourth')return occ===2||occ===4;if(raw==='first')return occ===1;if(raw==='second')return occ===2;if(raw==='third')return occ===3;if(raw==='fourth')return occ===4;if(raw==='specific_mondays')return dateListed(v,date);if(raw==='biweekly'||raw==='monthly')return dateListed(v,date);if(raw==='as_needed')return false;return false}
// Scheduling dropdown stays clean: name only when available; warning marker when availability needs checking.
function volunteerOption(v,date){const available=isVolunteerAvailable(v,date);return `<option value="${v.id}">${available?'':'⚠ '}${esc(v.name)}</option>`}
function floaterTeam(){return data.teams.find(t=>t.name.toLowerCase().includes('floater'))}
function volunteerTeamIds(v){return Array.isArray(v.team_ids)&&v.team_ids.length?v.team_ids:(v.primary_team_id?[v.primary_team_id]:[])}
function eligibleVolunteers(teamId){const floaterId=floaterTeam()?.id;return data.volunteers.filter(v=>{const ids=volunteerTeamIds(v);return ids.includes(teamId)||(floaterId&&ids.includes(floaterId))})}
function fillVolunteerChoices(date){const select=$('aVol');if(!select)return;const people=eligibleVolunteers($('aTeam').value);select.innerHTML=people.length?people.map(v=>volunteerOption(v,date)).join(''):'<option value="">No volunteers assigned to this team</option>';showAvailabilityNotice(date)}
function showAvailabilityNotice(date){const box=$('availabilityNotice'),v=vol($('aVol')?.value);if(!box)return;box.innerHTML=v?(isVolunteerAvailable(v,date)?'':`⚠ ${esc(v.name)} is <strong>not confirmed available</strong> for this Monday. You can still schedule them if they agreed to serve.`):'<span class="muted">No eligible volunteers are assigned to this team.</span>'}
window.addAssignment=date=>{const tOpts=data.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');modal(`<h2>Add to ${fmt(new Date(date+'T12:00:00'))}</h2><label>Team<select id="aTeam">${tOpts}</select></label><label>Position<select id="aPos"></select></label><label>Volunteer<select id="aVol"></select></label><div id="availabilityNotice" class="muted" style="margin-top:8px"></div><p class="muted">Only volunteers connected to the selected team are shown. Floaters are available to every team.</p>`,async()=>{const p=pos($('aPos').value),v=vol($('aVol').value);if(!p)throw Error('Please choose a valid position.');if(!v)throw Error('Please choose an eligible volunteer.');if(!eligibleVolunteers($('aTeam').value).some(x=>x.id===v.id))throw Error('That volunteer is not assigned to this team.');if(!isVolunteerAvailable(v,date)){const ok=confirm(`${v.name} is not confirmed available for ${fmt(new Date(date+'T12:00:00'))}.\n\nSchedule them anyway?`);if(!ok)throw Error('Scheduling cancelled.')}await api('save',{entity:'assignment',data:{service_date:date,team_id:$('aTeam').value,position_id:p.id,position_label:p.name,volunteer_id:v.id}})});const fillPositions=()=>{$('aPos').innerHTML=data.positions.filter(p=>p.team_id===$('aTeam').value).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')};$('aTeam').onchange=()=>{fillPositions();fillVolunteerChoices(date)};$('aVol').onchange=()=>showAvailabilityNotice(date);fillPositions();fillVolunteerChoices(date)};
window.editVolunteer=id=>{const v=id?vol(id):null,current=v?.availability_type||'weekly',normalized=current==='every_monday'?'weekly':['first_third','second_fourth'].includes(current)?'biweekly':['first','second','third','fourth'].includes(current)?'monthly':current,selected=new Set(v?volunteerTeamIds(v):[]);modal(`<h2>${v?'Edit':'Add'} Volunteer</h2><label>Name<input id="vName" required value="${esc(v?.name||'')}"></label><label>Phone<input id="vPhone" value="${esc(v?.phone||'')}"></label><label>Email<input id="vEmail" type="email" value="${esc(v?.email||'')}"></label><label>Primary Team<select id="vTeam">${data.teams.map(t=>`<option value="${t.id}" ${v?.primary_team_id===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>Teams this volunteer can serve on<div style="margin-top:6px">${data.teams.map(t=>`<label style="display:flex;gap:8px;align-items:center;margin:6px 0"><input class="vTeamCheck" type="checkbox" value="${t.id}" ${selected.has(t.id)?'checked':''} style="width:auto;margin:0"> ${esc(t.name)}</label>`).join('')}</div></label><p class="muted">Choose every team this person may be scheduled on. Volunteers connected to Floater can be selected for any team.</p><label>Availability<select id="vAvail">${AVAILABILITY_OPTIONS.map(([value,label])=>`<option value="${value}" ${normalized===value?'selected':''}>${label}</option>`).join('')}</select></label><p class="muted">Bi-weekly, monthly, as-needed, and specific-Monday volunteers show a warning when a Monday is not confirmed.</p><label>Volunteer Color<input id="vColor" type="color" value="${v?.personal_color||'#d9c7ef'}"></label><label>Notes<textarea id="vNotes">${esc(v?.notes||'')}</textarea></label>`,async()=>{const primary=$('vTeam').value,ids=[...document.querySelectorAll('.vTeamCheck:checked')].map(x=>x.value);if(!ids.includes(primary))ids.push(primary);await api('save',{entity:'volunteer',id,data:{name:$('vName').value.trim(),phone:$('vPhone').value.trim(),email:$('vEmail').value.trim(),primary_team_id:primary,team_ids:ids,availability_type:$('vAvail').value,personal_color:$('vColor').value,notes:$('vNotes').value}})});};
function renderVolunteers(){const root=$('volunteerList');root.className='volunteerTeams';root.innerHTML=data.teams.map(t=>{const people=data.volunteers.filter(v=>volunteerTeamIds(v).includes(t.id));return `<section class="volTeamGroup"><div class="volTeamHead" style="background:${t.color}"><strong>${esc(t.name)}</strong></div><div class="volGrid">${people.length?people.map(v=>`<div class="volCard"><div class="titleRow"><h3><i class="dot" style="background:${v.personal_color||'#eee'}"></i>${esc(v.name)}</h3><span><button type="button" onclick="editVolunteer('${v.id}')">Edit</button> <button type="button" onclick="deleteVolunteer('${v.id}')">Delete</button></span></div><div>${v.phone?`<a class="phone" href="tel:${v.phone.replace(/[^0-9+]/g,'')}">📞 ${esc(v.phone)}</a>`:'No phone'}</div><div>${esc(v.email||'')}</div><div class="muted">Availability: ${esc(availabilityLabel(v))}</div></div>`).join(''):'<div class="muted volEmpty">No volunteers on this team yet.</div>'}</div></section>`}).join('')}
window.deleteVolunteer=async id=>{const v=vol(id);if(!v)return;if(!confirm(`Delete ${v.name}'s volunteer profile?\n\nThis cannot be undone.`))return;try{await api('delete',{entity:'volunteer',id});await refresh()}catch(e){alert('Could not delete this volunteer: '+e.message)}};